{%- set B = xbuildout.encode -%}
/* SIB2/SIB3 for {{ cell.cell_type | upper }} cell {{ B(cell_ref) }} @ {{ B(ru_ref) }}. */
{
  message c1: systemInformation: {
{%- if cell.cell_type == 'lte' %}
    criticalExtensions systemInformation-r8: {
{%- elif cell.cell_type == 'nr' %}
    criticalExtensions systemInformation: {
{%- endif %}
      sib-TypeAndInfo {
        sib2: {
{%- if cell.cell_type == 'lte' %}
          radioResourceConfigCommon {
            rach-ConfigCommon {
              preambleInfo {
                numberOfRA-Preambles n52
              },
              powerRampingParameters {
                powerRampingStep dB{{ cell.advanced_parameter.prach_power_ramping_step }},
                preambleInitialReceivedTargetPower dBm{{ cell.advanced_parameter.prach_preamble_received_target_power }}
              },
              ra-SupervisionInfo {
                preambleTransMax n{{ cell.advanced_parameter.prach_preamble_trans_max }},
                ra-ResponseWindowSize sf10,
                mac-ContentionResolutionTimer sf40
              },
              maxHARQ-Msg3Tx 5
            },
            bcch-Config {
              modificationPeriodCoeff n4
            },
            pcch-Config {
              defaultPagingCycle rf128,
              nB oneT
            },
            prach-Config {
              rootSequenceIndex 0, /* patched by eNB */
              prach-ConfigInfo {
                prach-ConfigIndex 4, /* patched by eNB */
                highSpeedFlag FALSE,
                zeroCorrelationZoneConfig 11,
                prach-FreqOffset 4 /* patched by eNB */
              }
            },
            pdsch-ConfigCommon {
              referenceSignalPower -8, /* patched by eNB */
              p-b 1 /* patched by eNB */
            },
            pusch-ConfigCommon {
              pusch-ConfigBasic {
                n-SB 1,
                hoppingMode interSubFrame,
                pusch-HoppingOffset 8, /* patched by eNB */
                enable64QAM FALSE /* patched by eNB */
              },
              ul-ReferenceSignalsPUSCH {
                groupHoppingEnabled FALSE,
                groupAssignmentPUSCH 0,
                sequenceHoppingEnabled FALSE,
                cyclicShift 0
              }
            },
            pucch-ConfigCommon {
              deltaPUCCH-Shift ds2,
              nRB-CQI 4, /* patched by eNB */
              nCS-AN 0,
              n1PUCCH-AN 12 /* patched by eNB */
            },
            soundingRS-UL-ConfigCommon setup: {
              srs-BandwidthConfig bw2, /* patched by eNB */
              srs-SubframeConfig sc3, /* patched by eNB */
              ackNackSRS-SimultaneousTransmission TRUE
            },
            uplinkPowerControlCommon {
              p0-NominalPUSCH {{ cell.advanced_parameter.pusch_p0_nominal }},
              alpha al1,
              p0-NominalPUCCH {{ cell.advanced_parameter.pucch_p0_nominal }},
              deltaFList-PUCCH {
                deltaF-PUCCH-Format1 deltaF0,
                deltaF-PUCCH-Format1b deltaF3,
                deltaF-PUCCH-Format2 deltaF1,
                deltaF-PUCCH-Format2a deltaF2,
                deltaF-PUCCH-Format2b deltaF2
              },
              deltaPreambleMsg3 4
            },
            ul-CyclicPrefixLength len1
          },
          ue-TimersAndConstants {
            t300 ms200,
            t301 ms200,
            t310 ms200,
            n310 n6,
            t311 ms10000,
            n311 n5
          },
          freqInfo {
            additionalSpectrumEmission 1
          },
          timeAlignmentTimerCommon infinity
{%- elif cell.cell_type == 'nr' %}
          cellReselectionInfoCommon {
            q-Hyst dB{{ cell.advanced_parameter.q_hyst }}
          },
          cellReselectionServingFreqInfo {
            threshServingLowP 0,
            cellReselectionPriority {{ cell.advanced_parameter.cell_reselection_priority }}
          },
          intraFreqCellReselectionInfo {
            q-RxLevMin -70,
            s-IntraSearchP {{ cell.advanced_parameter.s_intra_search }},
            t-ReselectionNR {{ cell.advanced_parameter.t_reselection_nr }},
            smtc {
              periodicityAndOffset sf20: 0,
              duration sf1
            },
            ssb-ToMeasure mediumBitmap: '10000000'B,
            deriveSSB-IndexFromCell TRUE
          }
{%- endif %}
        },
{%- if cell.cell_type == 'lte' %}
        sib3: {
          cellReselectionInfoCommon {
            q-Hyst dB{{ cell.advanced_parameter.q_hyst }}
          },
          cellReselectionServingFreqInfo {
            s-NonIntraSearch 3,
            threshServingLow 2,
            cellReselectionPriority {{ cell.advanced_parameter.cell_reselection_priority }}
          },
          intraFreqCellReselectionInfo {
            q-RxLevMin -61,
            p-Max 23,
            s-IntraSearch {{ cell.advanced_parameter.s_intra_search }},
            presenceAntennaPort1 TRUE,
            neighCellConfig '01'B,
            t-ReselectionEUTRA {{ cell.advanced_parameter.t_reselection_eutra }}
          }
        }
{%- endif %}
      }
    }
  }
}
