#!/usr/bin/env python
r"""Command-line tool to format software release JSON for slapos.

Inspired by json.tool from python

Usage::

    format-json infile outfile

"""

import os
import sys
import json
import collections

def main():
    if len(sys.argv) != 3:
        raise SystemExit(sys.argv[0] + " infile outfile")

    infile = open(sys.argv[1], 'rb')
    with infile:
        try:
            obj = json.load(
                    infile,
                    object_pairs_hook=collections.OrderedDict)
        except ValueError, e:
            raise SystemExit(e)
    outfile = open(sys.argv[2], 'wb')

    with outfile:
        json.dump(obj, outfile, sort_keys=False,
                  indent=2, separators=(',', ': '))
        outfile.write('\n')


if __name__ == '__main__':
    main()
