#  policyd-spf configuration
#  See: https://www.linuxcertif.com/man/5/policyd-spf.conf/

# Disable logging because policyd-spf logs to syslog
debugLevel = -1

# Reject on HELO SPF failure
HELO_reject = SPF_Not_Pass

# Reject on Mail From SPF hard fail
Mail_From_reject = Fail

# Skip greylisting when Mail From SPF passes.
Mail_From_pass_restriction = spf_passed

# Do not reject on SPF permanent errors (e.g. broken DNS records)
PermError_reject = False

# Do not defer on SPF temporary errors (e.g. DNS timeout)
TempError_Defer = False

# Skip SPF checks for these addresses (loopback)
skip_addresses = 127.0.0.0/8,::ffff:127.0.0.0/104,::1