protocols = " imap lmtp sieve "

log_path = {{ dovecot_log_path }}

auth_debug = yes
auth_mechanisms = plain login
auth_username_format = %Lu
auth_verbose = yes
auth_debug_passwords = yes
auth_verbose_passwords = yes
disable_plaintext_auth = yes

base_dir = {{ dovecot_directory['run'] }}
state_dir = {{ dovecot_directory['var'] }}
mail_temp_dir = {{ dovecot_directory['tmp'] }}

default_internal_user = {{ user_name }}
default_login_user = {{ user_name }}
default_internal_group = {{ user_name }}

sendmail_path = {{ sendmail_path }}

mail_location = maildir:~/Maildir
mail_debug = yes
mail_plugin_dir = {{ dovecot_plugin_dir }}

ssl = required
ssl_cert = <{{ ssl_cert }}
ssl_key = <{{ ssl_key }}

protocol lda {
  mail_plugins = $mail_plugins sieve
}
protocol lmtp {
  mail_plugins = $mail_plugins sieve
}
protocol imap {
  mail_plugins = $mail_plugins imap_sieve
}

service anvil {
  chroot =
}

service imap-login {
  chroot =
  inet_listener imap {
    address = {{ ipv6 }}
    port = {{ imap_port }}
  }
  inet_listener imaps {
    address = {{ ipv6 }}
    port = {{ imaps_port }}
  }
}

service auth {
  unix_listener {{ postfix_auth }} {
    mode = 0660
    user = {{ user_name }}
    group = {{ user_name }}
  }
}

service lmtp {
  unix_listener {{ postfix_dovecot_lmtp }} {
    user = {{ user_name }}
    group = {{ user_name }}
    mode = 0600
  }
}

service managesieve-login {
  chroot =
  inet_listener sieve {
    address = {{ ipv6 }}
    port = 4190
  }
}

namespace inbox {
  inbox = yes
  location =
  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Junk {
    special_use = \Junk
  }
  mailbox Sent {
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
  mailbox Trash {
    special_use = \Trash
  }
  prefix =
}

passdb { 
  driver = passwd-file
  args = scheme=PLAIN username_format=%u {{ dovecot_passwd }}
}

userdb {
    driver = passwd-file
    args = username_format=%u {{ dovecot_passwd }}
    default_fields = uid={{ user_name }} gid={{ user_name }} home={{ dovecot_directory['home'] }}/%d/%n
}
plugin {
  # Used by both the Sieve plugin and the ManageSieve protocol
  sieve = file:~/sieve;active=~/.dovecot.sieve
  sieve_extensions = +editheader
  sieve_redirect_envelope_from = recipient

  {% if bogofilter_enable -%}
  # Sieve: run global filter before user sieve scripts on LMTP delivery
  sieve_before = {{ sieve_before }}

  # IMAPSieve: trigger retraining when messages are moved to/from Junk
  imapsieve_mailbox1_name = Junk
  imapsieve_mailbox1_causes = COPY APPEND
  imapsieve_mailbox1_before = file:{{ sieve_report_spam }}

  imapsieve_mailbox2_name = *
  imapsieve_mailbox2_from = Junk
  imapsieve_mailbox2_causes = COPY
  imapsieve_mailbox2_before = file:{{ sieve_report_ham }}

  sieve_pipe_bin_dir = {{ sieve_pipe_bin_dir }}
  sieve_global_extensions = +vnd.dovecot.pipe
  {%- endif %}
}

