{%- if _standalone is defined %}
{%-   do cell.setdefault('top_config', False) %}
{%- endif %}
{%- set B = xbuildout.encode -%}
/* SIB2/SIB3 for {{ cell.cell_type | upper }} cell {{ B(cell_ref) }} @ {{ B(ru_ref) }}. */
{
  message c1: systemInformation: {
    criticalExtensions systemInformation-r8: {
      sib-TypeAndInfo {
        sib2: {
          radioResourceConfigCommon {
            rach-ConfigCommon {
              preambleInfo {
                numberOfRA-Preambles n52,
{%- if cell.top_config %}
                preamblesGroupAConfig{
                  sizeOfRA-PreamblesGroupA n28,
                  messageSizeGroupA b56,
                  messagePowerOffsetGroupB dB10
                }
{%- endif %}
              },
              powerRampingParameters {
                powerRampingStep dB2,
                preambleInitialReceivedTargetPower dBm-104
              },
              ra-SupervisionInfo {
                preambleTransMax n10,
                ra-ResponseWindowSize sf10,
{%- if cell.top_config %}
                mac-ContentionResolutionTimer sf64
{%- endif %}
              },
              maxHARQ-Msg3Tx 5
            },
            bcch-Config {
{%- if cell.top_config %}
              modificationPeriodCoeff n2
{%- else %}
              modificationPeriodCoeff n4
{%- endif %}
            },
            pcch-Config {
{%- if cell.top_config %}
              defaultPagingCycle rf64,
{%- else %}
              defaultPagingCycle rf128,
{%- endif %}
              nB oneT
            },
            prach-Config {
              rootSequenceIndex 0, /* patched by eNB */
              prach-ConfigInfo {
{%- if cell.top_config %}
                prach-ConfigIndex 3, /* patched by eNB */
                zeroCorrelationZoneConfig 12,
                prach-FreqOffset 17 /* patched by eNB */
{%- else %}
                prach-ConfigIndex 4, /* patched by eNB */
                zeroCorrelationZoneConfig 11,
                prach-FreqOffset 4 /* patched by eNB */
{%- endif %}
                highSpeedFlag FALSE,
              }
            },
            pdsch-ConfigCommon {
{% if ors %}
{%- if ors['one-watt'] %}
              referenceSignalPower {{ (ru.tx_gain | int) - 54 }}, /* patched by eNB */
{%- else %}
              referenceSignalPower {{ (ru.tx_gain | int) - 35 }}, /* patched by eNB */
{%- endif %}
{% else %}
              referenceSignalPower -8, /* patched by eNB */
{% endif %}
              p-b 1 /* patched by eNB */
            },
            pusch-ConfigCommon {
              pusch-ConfigBasic {
                n-SB 1,
                hoppingMode interSubFrame,
                pusch-HoppingOffset 8, /* patched by eNB */
                enable64QAM FALSE /* patched by eNB */
              },
              ul-ReferenceSignalsPUSCH {
                groupHoppingEnabled FALSE,
                groupAssignmentPUSCH 0,
                sequenceHoppingEnabled FALSE,
                cyclicShift 0
              }
            },
            pucch-ConfigCommon {
              deltaPUCCH-Shift ds2,
              nRB-CQI 4, /* patched by eNB */
              nCS-AN 0,
              n1PUCCH-AN 12 /* patched by eNB */
            },
            soundingRS-UL-ConfigCommon setup: {
              srs-BandwidthConfig bw2, /* patched by eNB */
              srs-SubframeConfig sc3, /* patched by eNB */
              ackNackSRS-SimultaneousTransmission TRUE
            },
            uplinkPowerControlCommon {
              p0-NominalPUSCH -85,
              alpha al1,
              p0-NominalPUCCH -117,
              deltaFList-PUCCH {
                deltaF-PUCCH-Format1 deltaF0,
                deltaF-PUCCH-Format1b deltaF3,
                deltaF-PUCCH-Format2 deltaF1,
                deltaF-PUCCH-Format2a deltaF2,
                deltaF-PUCCH-Format2b deltaF2
              },
              deltaPreambleMsg3 4
            },
            ul-CyclicPrefixLength len1
          },
          ue-TimersAndConstants {
{%- if cell.top_config %}
            t300 ms600,
            t301 ms600,
            t310 ms2000,
            n310 n10,
            t311 ms5000,
            n311 n1
{%- else %}
            t300 ms200,
            t301 ms200,
            t310 ms200,
            n310 n6,
            t311 ms10000,
            n311 n5
{%- endif %}
          },
          freqInfo {
            additionalSpectrumEmission 1
          },
          timeAlignmentTimerCommon infinity
        },
        sib3: {
          cellReselectionInfoCommon {
            q-Hyst dB2
          },
          cellReselectionServingFreqInfo {
{%- if cell.top_config %}
            s-NonIntraSearch 21,
            threshServingLow 4,
{%- else %}
            s-NonIntraSearch 3,
            threshServingLow 2,
{%- endif %}
            cellReselectionPriority 6
          },
          intraFreqCellReselectionInfo {
            q-RxLevMin -61,
            p-Max 23,
{%- if cell.top_config %}
            s-IntraSearch 26,
{%- else %}
            s-IntraSearch 5,
{%- endif %}
            presenceAntennaPort1 TRUE,
            neighCellConfig '01'B,
            t-ReselectionEUTRA 1
          }
        }
      }
    }
  }
}
